name: Build Artifacts

on:
  push:
    branches:
      - develop
      - release/*
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows

    steps:
      - name: Get short commit hash
        id: get-commit-hash
        run: |
          hash=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "hash=${hash}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.5"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked

      - name: Bundle with PyInstaller
        run: |
          uv run pyinstaller yarl.spec --noconfirm
          cp LICENSE ./dist/yarl/
          mv ./dist/yarl "./dist/yarl_${{ matrix.platform }}_${{ matrix.arch }}_${{ github.ref_name }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: yarl_${{ matrix.platform }}_${{ matrix.arch }}_${{ steps.get-commit-hash.outputs.hash }}
          path: ./dist/
